#
#  Copyright (c) 2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#
---

################################
# EDC ControlPlane + DataPlane #
################################

# Log4j2 configuration - required for 0.11.2+
log4j2:
  enableJsonLogs: true
  config: |-
    Appenders:
      Console:
        name: CONSOLE
        JsonTemplateLayout:
          eventTemplate: |-
            {
              "timestamp": {
                "$resolver": "timestamp",
                "pattern": {
                  "format": "yyyy-MM-dd'T'HH:mm:ss.SSSSSSS",
                  "timeZone": "UTC"
                }
              },
              "level": {
                "$resolver": "level",
                "field": "severity",
                "severity": {
                  "field": "keyword"
                }
              },
              "message": {
                "$resolver": "message"
              }
            }
    Loggers:
      Root:
        level: "OFF"
      Logger:
        - name: org.eclipse.edc.monitor.logger
          level: DEBUG
          AppenderRef:
            ref: CONSOLE
        - name: org.eclipse.edc.iam.identitytrust
          level: TRACE
          AppenderRef:
            ref: CONSOLE
        - name: org.eclipse.edc.iam.identitytrust.core
          level: TRACE
          AppenderRef:
            ref: CONSOLE
        - name: org.eclipse.edc.iam.identitytrust.transform
          level: TRACE
          AppenderRef:
            ref: CONSOLE
        - name: org.eclipse.edc.iam.identitytrust.spi
          level: TRACE
          AppenderRef:
            ref: CONSOLE
        - name: org.eclipse.edc.token
          level: DEBUG
          AppenderRef:
            ref: CONSOLE
        - name: org.eclipse.tractusx.edc.iam
          level: DEBUG
          AppenderRef:
            ref: CONSOLE
        - name: org.eclipse.tractusx.edc.iam.iatp
          level: TRACE
          AppenderRef:
            ref: CONSOLE
        - name: org.eclipse.tractusx.edc.iam.dcp.sts
          level: TRACE
          AppenderRef:
            ref: CONSOLE

participant:
  id: "test-participant"
controlplane:
  debug:
    enabled: true
    port: 1044
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
  service:
    type: NodePort
  endpoints:
    management:
      authKey: password
# uncomment the following lines if a custom tx-control-plane runtime images should be used.
  image:
    pullPolicy: Always
    repository: "tractusx/edc-controlplane-postgresql-hashicorp-vault"
    tag: "0.11.2"

  securityContext:
    # avoids some errors in the log: cannot write temp files of large multipart requests when R/O
    readOnlyRootFilesystem: false
dataplane:
  debug:
    enabled: true
    port: 1044
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
  image:
    pullPolicy: Always
    repository: "tractusx/edc-dataplane-hashicorp-vault"
    tag: "0.11.2"
  securityContext:
    # avoids some errors in the log: cannot write temp files of large multipart requests when R/O
    readOnlyRootFilesystem: false
  aws:
    endpointOverride: http://minio:9000
    secretAccessKey: qwerty123
    accessKeyId: qwerty123

postgresql:
   # JDBC URL should be set from `main.tf`
   jdbcUrl:
#  jdbcUrl: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/edc
   auth:
     username:
     password:
vault:
    hashicorp:
      url: http://{{ .Release.Name }}-vault:8200
      token: root
      paths:
        secret: /v1/secret
    secrets:
backendService:
  httpProxyTokenReceiverUrl: "http://backend:8080"
tests:
  hookDeletePolicy: before-hook-creation
